This is makeindex, version 2.16 [MiKTeX 25.12].
Scanning style file ./memoireNdzessaAvele.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file memoireNdzessaAvele.acn....done (64 entries accepted, 0 rejected).
Sorting entries....done (393 comparisons).
Generating output file memoireNdzessaAvele.acr....done (60 lines written, 0 warnings).
Output written in memoireNdzessaAvele.acr.
Transcript written in memoireNdzessaAvele.alg.
